services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - neumont_market
  
  express:
    build: ./chat
    ports:
      - 10101:10101
    depends_on:
      - cassandra
    networks:
      - neumont_market

volumes:
  cassandra_data:

networks:
  neumont_market: